"""first migration

Revision ID: 5d3dfe0fbadd
Revises: 
Create Date: 2024-10-30 15:21:41.052076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d3dfe0fbadd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_word_phonology'), ['phonology'], unique=False)
        batch_op.create_index(batch_op.f('ix_word_spelling'), ['spelling'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_word_spelling'))
        batch_op.drop_index(batch_op.f('ix_word_phonology'))

    # ### end Alembic commands ###
